version: "3"
services:
  elasticsearch:
    image: elasticsearch:8.10.2
    container_name: elasticsearch
    labels:
      - co.elastic.logs/enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: single-node
      xpack.security.enabled: false
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: kibana:8.10.2
    container_name: kibana
    restart: unless-stopped
    labels:
      - co.elastic.logs/enabled=false
    networks:
      - elastic
    ports:
      - "5601:5601"
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    depends_on:
      - elasticsearch
    volumes:
      - ./configs/kibana.yml:/usr/share/kibana/config/kibana.yml

  logstash:
    image: logstash:8.10.2
    container_name: logstash
    labels:
      - co.elastic.logs/enabled=false
    restart: unless-stopped
    depends_on:
      - elasticsearch
    networks:
      - elastic
    ports:
      - "5044:5044"
    volumes:
      - ./configs/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline/:/usr/share/logstash/pipeline
  filebeat:
    user: root
    image: elastic/filebeat:8.10.2
    container_name: filebeat
    labels:
      - co.elastic.logs/enabled=false
    restart: unless-stopped
    networks:
      - elastic
    volumes:
      - ./configs/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    environment:
      strict.perms: false
    depends_on:
      - logstash
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
networks:
  elastic:
    name: elastic
    driver: bridge
volumes:
  elasticsearch-data: {}
