filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      # hints.enabled: true
      templates:
        - condition:
            equals:
              docker.container.labels.co.elastic.logs/enabled: "true" # only send metrics with explicit hints
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              exclude_lines: ["\\s+[\\-`('.|_]"]
processors:
  - dissect:
      tokenizer: "%{timestamp} [%{status_code}] %{method} %{uri} %{ip_address} [%{uagent}] RT:%{msecs} REF:%{referer} SZ:%{size} %{proto}"
      field: "message"
      target_prefix: ""
output.logstash:
  hosts: ["logstash:5044"]
